### ISSUE TITLE
 Error generating LTSAs

### ISSUE THREAD

**Issue by laralps** [MarineBioAcousticsRC/Triton#85]
Dear all,

I'm new to using triton. So far, I'm having trouble generating LTSAs. I am getting the error message: 
"Error using horzcat: Dimensions of arrays being concatenated are not consistent." See:

```
Error using horzcat
Dimensions of arrays being concatenated are not consistent.

Error in calc_ltsa (line 149)
                               data = [data,dz'];

Error in mk_ltsa (line 43)
calc_ltsa

Error in toolpd (line 81)
  mk_ltsa
 
Error while evaluating Menu Callback.
```

Data was collected with anchored SoundTraps recording at 96kHz and 16-bit continuously for two months (each file containing 10 minutes). All audio files have the same size. What could be happening, can you please shed some light? 

Thanks for the support,

**Comment by sfregosi** [comment]
@laralps this bug is due to the differences in which wavs are read into Matlab, compared to xwavs (which is the file format Triton was originally created to work best with). 

I added this on a [comment on a different commit](https://github.com/MarineBioAcousticsRC/Triton/commit/f34b0b58a40b9fafaebadae756eb1815fd94d41a#commitcomment-76857191) but I am realizing now I should have fixed and put in as a pull request. 

I will work on that, but for now, you can do the following to fix it:

in calc_ltsa.m, replace line 149 (`data = [data,dz'];`) with the code below:

```
            if size(data,1) > 1 % column vector, typical for wav/flac
                data = [data;dz]; 
            elseif size(data,2) > 1 % row vector, typical for xwav
                data = [data,dz'];
            end
```

**Comment by laralps** [comment]
Yeah, it worked, thanks!
